### ISSUE TITLE
Exception : 'NoneType' object has no attribute 'amount'

### ISSUE THREAD

**Issue by junkscript** [samirsalman/AmazonOffers-TelegramBot#10]
Hello @samirsalman,
Every time I launch the bot command the script starts to run but often gives an error: 

`Exception: 'NoneType' object has no attribute 'amount'`

How can this error be resolved?
Thanks for your time

**Comment by luisafurtadodnv** [comment]
I am having the same issue

**Comment by Lollai** [comment]
> 

Solved?
