### ISSUE TITLE
Hours and Hours of search 

### ISSUE THREAD

**Issue by junkscript** [samirsalman/AmazonOffers-TelegramBot#11]
Hello  @samirsalman, 
I have entered 5 words in the list of keywords, chosen the category in which to search, everything seems to work but the bot continues for hours to return only the message: Request received
He continues to grind objects upon objects but in the end he does not post any results on the telegram group. Why is the bot unable to finalize the search for objects?
Thanks for your time and help

**Comment by Tahmid-Hossain-287** [comment]
> Hi junkscript, can you add more information about your issue? e.g. The bot init code and the logs

Hello Smair Salman, you've done a great work. I am curious why do you deduct 2 hours from min hours and max hours in line 70 of bot.py? Should you not just check ``` if MIN_HOUR < now.hour < MAX_HOUR:```?
Sorry if it is inappropriate to ask question in this issue but I could find no way of contacting you.
