### ISSUE TITLE
'Bot' object has no attribute 'send_message'

### ISSUE THREAD

**Issue by alek911** [samirsalman/AmazonOffers-TelegramBot#13]
Hello, can someones help me? When I run the bot I obtain this error in shell and no post in telegram channel.

Request received
Request received
Request received
***** Requests Completed *****
***** Creating post *****
***** Sending posts to channel *****
'Bot' object has no attribute 'send_message'
***** Sending posts to channel *****
'Bot' object has no attribute 'send_message'

I have edited the bot.py with botfathers token and channel id and the amazon_api with my aapi keys. What's wrong?

How can I fix it?
Thank you

**Comment by alek911** [comment]
same error with channel name instead of channel's id

**Comment by alek911** [comment]
After reinstall I receive this error:
***** Sending posts to channel *****
Object of type InlineKeyboardMarkup is not JSON serializable
***** Sending posts to channel *****
Unauthorized

**Comment by alek911** [comment]
solved (wrong character in token).
Sometimes got "Object of type InlineKeyboardMarkup is not JSON serializable" but the bot works.

**Comment by hitesh1435** [comment]
Hello can you help me how did you setup

**Comment by alek911** [comment]
I have fix my problems in this way:
reinstall bot using python3
set the right bot's token (I have mistyped the first time)
set the channel name (you have to set public channel and set channel link.
in my case t.me/aklabofferte : @aklabofferte is the channel name to use)
set the bot admin of channel


Il giorno lun 20 dic 2021 alle ore 05:27 hitesh1435 <
***@***.***> ha scritto:
