### ISSUE TITLE
please help!

### ISSUE THREAD

**Issue by LostTree0071** [samirsalman/AmazonOffers-TelegramBot#26]
hi samir i need help, when i start the bot keeps saying request received but does not create the message says: Exception: 'NoneType' object has no attribute 'savings'
INFO: root: 'NoneType' object is not iterable how can I solve?

**Comment by Lollai** [comment]
> hi samir i need help, when i start the bot keeps saying request received but does not create the message says: Exception: 'NoneType' object has no attribute 'savings' INFO: root: 'NoneType' object is not iterable how can I solve?

You solved?
