### ISSUE TITLE
api info

### ISSUE THREAD

**Issue by Peppuss** [samirsalman/AmazonOffers-TelegramBot#28]
HI

`AMAZON_ACCESS_KEY = "<YOUR AMAZON ACCESS KEY>"
AMAZON_SECRET_KEY = "<YOUR AMAZON SECRET KEY>"
PARTNER_TAG = "<YOUR AMAZON PARTNER TAG>"
AMAZON_HOST = "<YOUR AMAZON HOST>"
AMAZON_REGION = "<YOUR AMAZON REGION>"`

Where i can find this? how i create

**Comment by hardcore** [comment]
You can find this information in your amazon partnernet account. 

You can apply for the amazon affiliate program. By searching "amazon affiliate program <your country>" at google you'll find the right program.
