### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Lollai** [samirsalman/AmazonOffers-TelegramBot#29]
I keep getting this error: 

Exception: 'NoneType' object has no attribute 'savings'
INFO: root: 'NoneType' object is not iterable

The APIs are correct, I have tested them. Has anyone solved it?

**Comment by Lollai** [comment]
Solved.
You have to pay attention to the categories.

**Comment by Lollai** [comment]
Solved.
You have to pay attention to the categories.

**Comment by uweb-it** [comment]
Same problem

Exception: 'NoneType' object has no attribute 'savings'
INFO: root: 'NoneType' object is not iterable

solutions?
