### ISSUE TITLE
Amazon API 

### ISSUE THREAD

**Issue by Bomber75** [samirsalman/AmazonOffers-TelegramBot#36]
Hi all,
how do you recover this data?
with AWS AMAZON lamda?

does the host have to be amazon?
or can I choose other hosts?

AMAZON_ACCESS_KEY = "<YOUR AMAZON ACCESS KEY>"
AMAZON_SECRET_KEY = "<YOUR AMAZON SECRET KEY>"

AMAZON_HOST = "<YOUR AMAZON HOST>"
AMAZON_REGION = "<YOUR AMAZON REGION>"

Thank you for your attention

**Comment by patacalas** [comment]
Hi
You can get Amazon Keys from your affiliates account.
Host and region information check here https://webservices.amazon.com/paapi5/documentation/add-to-cart-form.html
