### ISSUE TITLE
Help me! 

### ISSUE THREAD

**Issue by Alex87a** [samirsalman/AmazonOffers-TelegramBot#4]
Hi, I am approaching your bot for the first time and I am truly amazed!  However, being new to this language, I would have problems:

1) I did not understand what parameters I have to put in these fields, especially in the first two.  Should I put my email and password? 
# ***** Amazon API Keys and parameters *****
access_key = "<YOUR AMAZON ACCESS KEY>"
secret_key = "<YOUR AMAZON SECRET KEY>"
partner_tag = "<YOUR AMAZON PARTNER TAG>"
host = "<YOUR AMAZON HOST>"
region = "<YOUR AMAZON REGION>"

2) I would be interested in cloning it however I don't know how to do it.  What programs do you need to download?

**Comment by fabrizio-medusa** [comment]
anche io sarei interessato alle chiavi API..
So bene che bisogna ottenere le PA API direttamente da amazon ma bisogna aver fatto prima 3 vendite.. Al momento non ho venduto niente e vorrei sapere se è possibile utilizzare delle altre API...
Grazie.

**Comment by samirsalman** [comment]
Hi,
all of these parameters are given from the amazon affiliation program.
