### ISSUE TITLE
AMAZON_HOST

### ISSUE THREAD

**Issue by giuseppe30** [samirsalman/AmazonOffers-TelegramBot#41]
what information needs AMAZON_HOST and AMAZON_REGION ?

**Comment by paolofrancioso** [comment]
Ciao Giuseppe (hi),

Check this link: https://webservices.amazon.com/paapi5/documentation/common-request-parameters.html#host-and-region

If you are in Italy as I think, you are looking for these two:
amazon_host webservices.amazon.it
amazon_region eu-west-1

**Comment by giuseppe30** [comment]
grazie!

**Comment by paolofrancioso** [comment]
Di nulla :)
