### ISSUE TITLE
INFO:root:'NoneType' object is not iterable Exception : ('Connection aborted.', InvalidURL("URL can't contain control characters. '<your amazon host>' (found at least ' ')")) 

### ISSUE THREAD

**Issue by huseyin0911** [samirsalman/AmazonOffers-TelegramBot#47]
i do everything in the description, but i have this issues. Im doing it for the amazon in germany. Can you help me?

INFO:root:'NoneType' object is not iterable
Exception : ('Connection aborted.', InvalidURL("URL can't contain control characters. '<your amazon host>' (found at least ' ')"))
INFO:root:'NoneType' object is not iterable
Exception : ('Connection aborted.', InvalidURL("URL can't contain control characters. '<your amazon host>' (found at least ' ')"))
INFO:root:'NoneType' object is not iterable
Exception : ('Connection aborted.', InvalidURL("URL can't contain control characters. '<your amazon host>' (found at least ' ')"))
INFO:root:'NoneType' object is not iterable

**Comment by samirsalman** [comment]
Check the const you provided
